apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatisation-deployment
  namespace: default
  labels:
    app: automatisation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: automatisation
  template:
    metadata:
      labels:
        app: automatisation
    spec:
      containers:
        - name: automatisation-container
          image: p4vl1n/automatisation_avec_ansible:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

