apiVersion: v1
kind: Service
metadata:
  name: automatisation-service
  namespace: default
  labels:
    app: automatisation
spec:
  selector:
    app: automatisation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

